name: 'Chromatic'

on:
  push:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - 'tests/**'

  pull_request:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - 'tests/**'

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "PRICES_LIST_ENDPOINT=${{ secrets.PRICES_LIST_ENDPOINT }}" >> $GITHUB_ENV
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
      - name: Install npm
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: './storybook-static'
