name: 'Chromatic'

on:
  push:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - '!tests/**'

  pull_request:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - '!tests/**'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: node setup composite
        uses: ./.github/actions/setup-node-cache
      - name: Build Storybook
        run: npx storybook build
      - name: Move Storybook static files
        run: mv storybook-static ../
      - name: Deploy Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} || echo "status=$?" >> $GITHUB_OUTPUT

        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
