name: 'Chromatic'

on:
  push:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - '!tests/**'

  pull_request:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - '!tests/**'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy chromatic
        run: |
          npm
          npm build-storybook
          mv storybook-static ../
          yarn chromatic \
            --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} || echo "status=$?" >> $GITHUB_OUTPUT
