name: Run Eslint

on:
  workflow_run:
    workflows: ['Caching with npm']
    types:
      - completed

jobs:
  eslint:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Lint
        run: npm run lint
