name: Run Eslint

on:
  pull_request_target:
    branches:
      - main
    paths:
      - '!.*'
      - '!.vscode/**'
      - 'app/**'
      - '.github/**'

jobs:
  checkout-install-dependencies:
    uses: ./.github/workflows/common.yml

  lint:
    runs-on: ubuntu-latest
    needs: checkout-install-dependencies
    steps:
      - name: Run Lint
        run: npm run lint
