name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js with cache
        uses: ./.github/actions/setup-node-cache

      - name: Check if app/ directory has changes
        id: changes
        run: |
          if git diff --name-only origin/main... | grep '^app/'; then
            echo "shouldRun=true" >> $GITHUB_OUTPUT
          else
            echo "shouldRun=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Unit Tests
        if: steps.changes.outputs.shouldRun == 'true'
        run: npm run test:unit

      - name: Skip Tests (no app/ changes)
        if: steps.changes.outputs.shouldRun == 'false'
        run: echo "No app/ changes detected. Skipping tests."
