name: Run Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/**'
  pull_request_target:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/**'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect_changes.outputs.changes }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changes
        id: detect_changes
        run: |
          git fetch origin main
          CHANGES=$(git diff --name-only origin/main...HEAD)
          echo "Detected changes: $CHANGES"
          if echo "$CHANGES" | grep -qE '^app/|^\.github/'; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"

  test:
    needs: check_changes
    if: needs.check_changes.outputs.changes == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm
        run: npm install

      - name: Run Tests
        env:
          URL: ${{ secrets.URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm test
