name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - 'tests/**'

  pull_request:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: node setup composite
        uses: ./.github/actions/setup-node-cache

      - name: Run Tests
        run: npm test
