name: Run Tests

on:
  pull_request_target:
    branches:
      - main
    paths:
      - '!.*'
      - 'app/**'
      - '.github/**'
      - 'tests/**'

jobs:
  checkout-install-dependencies:
    uses: ./.github/workflows/common.yml

  test:
    runs-on: ubuntu-latest
    needs: checkout-install-dependencies
    steps:
      - name: Run Tests
        run: npm test
